import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../src/botao'

export default function Coils() {
  return (
    <div className={styles.container}>
      <Head>
        <title>S C & Coils - Coils</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className={styles.main}>
      <div className={styles.title}>
        <h1>SC & Coils</h1>
      <div className={styles.description}>
      <h5>Itens Para uma build perfeita</h5>
        </div>   </div>
            <div className={styles.row}>
                <div className={styles.column}>
                <Image
                src="/coilsimples.jpg"
                alt="Simples"
                width={200}
                height={200}
                />
                </div>

                <div className={styles.column}>
                <Image
                src="/coilparalela.jpg"
                alt="paralela"
                width={200}
                height={200}
                />
                </div>

                <div className={styles.column}>
                <Image
                src="/coiltwisted.jpg"
                alt="Simples"
                width={200}
                height={200}
                /> 
                </div>

                <div className={styles.column}>
                <Image
                src="/coilclapton.jpg"
                alt="Simples"
                width={200}
                height={200}
                />
                </div>
            </div>
        

      </main>  
    </div>
  )
}
