import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../src/botao'

export default function Coils() {
  return (
    <div className={styles.container}>
      <Head>
        <title>S C & Coils - Coils</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className={styles.main}>
      <div className={styles.title}>
        <h1>SC & Coils</h1>
      <div className={styles.description}>
      <h5>Itens Para uma build perfeita</h5>
      </div>  
      </div>
      <div className={styles.lista}>
      Tipos de Coils
         <ul>
             <li>Simples<Image
        src="/coilsimples.jpg"
        alt="Coils"
        width={100}
        height={100}
      /></li>
             <li>Paralelas<Image
        src="/coilparalela.jpg"
        alt="Coils"
        width={100}
        height={100}
      /></li>
             <li>Twisted<Image
        src="/coiltwisted.jpg"
        alt="Coils"
        width={100}
        height={100}
      /></li>
             <li>Clapton<Image
        src="/coilclapton.jpg"
        alt="Coils"
        width={100}
        height={100}
      /></li>
         </ul>
          
      </div>

      </main>  
    </div>
  )
}
